name: disparo-manual

on:
  workflow_dispatch:
    inputs:
      texto:
        description: 'Mensaje completo (puede incluir @menciones)'
        required: true
        type: string

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - run: |
          node - <<'JS'
          const fetch = global.fetch // Node 20 trae fetch
          await fetch(process.env.DISCORD_WEBHOOK, {
            method: 'POST',
            headers: { 'Content-Type':'application/json' },
            body: JSON.stringify({ content: process.env.MENSAJE })
          })
JS
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MENSAJE:            ${{ github.event.inputs.texto }}