name: disparo-manual

on:
  workflow_dispatch:
    inputs:
      texto:
        description: 'Mensaje (incluye @menciones)'
        required: true
        type: string

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: enviar
        run: |
          curl -s -X POST \
               -H "Content-Type: application/json" \
               -d "{\"content\":\"${MENSAJE}\"}" \
               "$DISCORD_WEBHOOK"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MENSAJE:         ${{ github.event.inputs.texto }}
