name: avisos-cada-5-min

on:
  schedule:
    - cron: '*/5 * * * *'     # cada 5 min UTC
jobs:
  send:
    runs-on: ubuntu-latest
    env: { TZ: America/Asuncion }
    steps:
      - uses: actions/checkout@v4
      - run: node scripts/send.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
